// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGh7MjCKEpUKLJcf9_IMsBufhzpmeX9WU',
    appId: '1:107745422947:web:39615b3845fb0a876c5256',
    messagingSenderId: '107745422947',
    projectId: 'vitorkanofooddelivery',
    authDomain: 'vitorkanofooddelivery.firebaseapp.com',
    storageBucket: 'vitorkanofooddelivery.appspot.com',
    measurementId: 'G-TBHE30LS87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF2fynr8UafNaWQ3tJ__yJV0da1-RojIk',
    appId: '1:107745422947:android:83dfc73df33bd2346c5256',
    messagingSenderId: '107745422947',
    projectId: 'vitorkanofooddelivery',
    storageBucket: 'vitorkanofooddelivery.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6g9a9pTBPs4j4qeloZO9Vv02D3rk9GLo',
    appId: '1:107745422947:ios:b4f83a6eb86298b96c5256',
    messagingSenderId: '107745422947',
    projectId: 'vitorkanofooddelivery',
    storageBucket: 'vitorkanofooddelivery.appspot.com',
    iosBundleId: 'com.example.foodDeliveryAppBackend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6g9a9pTBPs4j4qeloZO9Vv02D3rk9GLo',
    appId: '1:107745422947:ios:b4f83a6eb86298b96c5256',
    messagingSenderId: '107745422947',
    projectId: 'vitorkanofooddelivery',
    storageBucket: 'vitorkanofooddelivery.appspot.com',
    iosBundleId: 'com.example.foodDeliveryAppBackend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGh7MjCKEpUKLJcf9_IMsBufhzpmeX9WU',
    appId: '1:107745422947:web:be5ad78f6c52ecc16c5256',
    messagingSenderId: '107745422947',
    projectId: 'vitorkanofooddelivery',
    authDomain: 'vitorkanofooddelivery.firebaseapp.com',
    storageBucket: 'vitorkanofooddelivery.appspot.com',
    measurementId: 'G-ZD682T74Q4',
  );
}